### ISSUE TITLE
Time active is constantly increasing and it activates seemingly randomly

### ISSUE THREAD

**Issue by 05b001** [ChemicalXandco/simple-clicker#2]
The time that says how long the simple clicker is active did not stop after I let go, so it continued up to around 1023 seconds. Also, it seems to be activating randomly, with after it randomly decided that it's active, it then executes the hotkey. I think this might be due to it having huge trouble with spam clicks. Also, while it's randomly active and counting up, the application is unresponsive until it decided that it'll actually perform the hotkey and then it'll end counting and you can interact with the application again. The logs contain absolutely nothing useful. I'm not sure yet why all of this is happening, I'll play around with it later. I'm running it in windows.

**Comment by ChemicalXandco** [comment]
Hotkey is not meant to be held, press once to activate, press again to deactivate. Careful when deactivating because you cannot deactivate while an option is running.

**Comment by 05b001** [comment]
Thanks, you might want to add in some protection against that.
